-- Per-system go-live readiness. Systems become the source of truth for readiness;
-- cluster figures are counted from them. Seeded with Phase 1A and 1B from the
-- 252 Systems Workplan (Phase 1 Workplan sheet).

DROP TABLE clusters;

CREATE TABLE clusters (
  code       varchar(10)  PRIMARY KEY,
  name       varchar(100) NOT NULL,
  sort_order smallint     NOT NULL
);

INSERT INTO clusters (code, name, sort_order) VALUES
  ('C1', 'Governance, Board, Statutory & Records', 1),
  ('C2', 'Accreditation, Quality Assurance & Inspectorate', 2),
  ('C3', 'Student & Academic Lifecycle', 3),
  ('C4', 'Learning, Research & Knowledge Services', 4),
  ('C5', 'Assessment & Examinations', 5),
  ('C6', 'Communications, Brand & Stakeholder Engagement', 6),
  ('C7', 'People, Talent & Culture (HR)', 7),
  ('C8', 'Finance, Procurement & Resource Mobilisation', 8),
  ('C9', 'Safety, Facilities & Logistics', 9),
  ('C10', 'Compliance, Risk, Audit & Data Protection', 10),
  ('C11', 'IT Operations, Cybersecurity & Platform', 11),
  ('C12', 'Analytics, Data & Artificial Intelligence', 12);

CREATE TABLE systems (
  id           serial PRIMARY KEY,
  code         varchar(20)  NOT NULL UNIQUE,
  name         varchar(200) NOT NULL,
  cluster_code varchar(10)  NOT NULL REFERENCES clusters(code),
  phase        varchar(4)   NOT NULL,
  notes        text,
  ready        boolean      NOT NULL DEFAULT false,
  sort_order   smallint     NOT NULL DEFAULT 0,
  updated_at   timestamptz,
  updated_by   integer REFERENCES admins(id)
);

INSERT INTO systems (code, name, cluster_code, phase, notes, sort_order) VALUES
  ('S001', 'Governance Portal', 'C1', '1A', NULL, 1),
  ('S002', 'Board Document Management System', 'C1', '1A', NULL, 2),
  ('S003', 'Records Management System (System 05)', 'C1', '1A', NULL, 3),
  ('S010', 'Conflict-of-Interest Declaration Portal (entity-wide)', 'C1', '1A', NULL, 4),
  ('S015', 'IT Project & Portfolio Management (PPM)', 'C1', '1A', NULL, 5),
  ('S012', 'Code-of-Conduct Acknowledgement & Annual Attestation Engine', 'C1', '1A', NULL, 6),
  ('S008', 'NBEC Management Portal', 'C1', '1A', NULL, 7),
  ('S013', 'Compliance Obligations Register', 'C1', '1A', NULL, 8),
  ('S094', 'Institutional Self-Assessment / SAR Portal', 'C2', '1A', NULL, 9),
  ('S048', 'Accreditation System', 'C2', '1A', NULL, 10),
  ('S096', 'Complaints, Whistleblowing & Tip-Off Intake (QA)', 'C2', '1A', NULL, 11),
  ('S099b', 'Action-Plan & Conditions Management for Suspended Licences', 'C2', '1A', NULL, 12),
  ('S099c', 'QA Cycle Calendar & Auto-Deadline Engine', 'C2', '1A', NULL, 13),
  ('S027', 'NLEMS / Student Information System (System 01)', 'C3', '1A', NULL, 14),
  ('S032', 'Student Welfare & Counselling Case Management', 'C3', '1A', NULL, 15),
  ('S046', 'Lecture Capture & Video-on-Demand', 'C3', '1A', NULL, 16),
  ('S104', 'Integrated Library Management System (ILS)', 'C4', '1A', 'Yet to decouple', 17),
  ('S110', 'Legal Research Database Integrations', 'C4', '1A', 'Yet to decouple', 18),
  ('S060', 'Examiner & Moderator Roster Management', 'C5', '1A', NULL, 19),
  ('S061', 'Item Bank with Psychometric Analytics (IRT/Rasch)', 'C5', '1A', NULL, 20),
  ('S063', 'NBES — National Bar Examination System', 'C5', '1A', NULL, 21),
  ('S064', 'Examination Infrastructure / CBT Delivery (System 10B)', 'C5', '1A', NULL, 22),
  ('S067', 'Standard-Setting / Pass-Mark Determination Tool', 'C5', '1A', NULL, 23),
  ('S068', 'Question-Paper Secure Authoring & Vault', 'C5', '1A', NULL, 24),
  ('S069', 'Distributed / Marking-Centre Platform', 'C5', '1A', NULL, 25),
  ('S062', 'Examination Verification System (System 03)', 'C5', '1A', NULL, 26),
  ('S090_crisis', 'Reputation & Crisis-Comms Playbook System', 'C6', '1A', 'Clarification from SRS Team Needed', 27),
  ('S089', 'Intranet / Staff Engagement Portal', 'C6', '1A', NULL, 28),
  ('S074', 'Comms System (System 21)', 'C6', '1A', NULL, 29),
  ('S075', 'Newsletter / Email Marketing Automation', 'C6', '1A', NULL, 30),
  ('S076', 'Public-Facing Website CMS (marketing site)', 'C6', '1A', NULL, 31),
  ('S077', 'Bulk SMS Gateway', 'C6', '1A', NULL, 32),
  ('S081', 'Stakeholder / Partner CRM', 'C6', '1A', NULL, 33),
  ('S140', 'HR Management System (System 09)', 'C7', '1A', NULL, 34),
  ('S143', 'Applicant Tracking System (ATS)', 'C7', '1A', NULL, 35),
  ('S145_bgc', 'Pre-Employment Background-Check Integration', 'C7', '1A', NULL, 36),
  ('S148_time', 'Time & Attendance with Biometric Clocking', 'C7', '1A', NULL, 37),
  ('S149_pen', 'Pension & Benefits Administration', 'C7', '1A', NULL, 38),
  ('S150_tax', 'Payroll Tax / GRA Filing Automation', 'C7', '1A', NULL, 39),
  ('S141_pay', 'Payment System (System 20)', 'C7', '1A', NULL, 40),
  ('S132', 'e-Procurement / Sourcing Suite (PPRA-compliant)', 'C8', '1A', NULL, 41),
  ('S133', 'Vendor Master & Supplier Self-Service Portal', 'C8', '1A', NULL, 42),
  ('S135', 'Purchase Order & 3-Way Match Engine', 'C8', '1A', NULL, 43),
  ('S138', 'Financial Management System', 'C8', '1A', NULL, 44),
  ('S140fin', 'Tax Compliance & Filings', 'C8', '1A', NULL, 45),
  ('S141', 'Payment System (System 20)', 'C8', '1A', NULL, 46),
  ('S147', 'Asset Register / Fixed-Asset Management', 'C8', '1A', NULL, 47),
  ('S190fin', 'Anti-Bribery & Corruption Vendor Due-Diligence', 'C8', '1A', NULL, 48),
  ('S152', 'Computer-Aided Facility Management (CAFM) / IWMS', 'C9', '1A', NULL, 49),
  ('S153', 'Computerised Maintenance Management System (CMMS)', 'C9', '1A', NULL, 50),
  ('S159', 'Room & Resource Booking System', 'C9', '1A', NULL, 51),
  ('S166', 'Fleet & Vehicle Management', 'C9', '1A', NULL, 52),
  ('S168_fuel', 'Fuel Management & Driver Logbooks', 'C9', '1A', NULL, 53),
  ('S171', 'Mailroom / Courier & Despatch Tracking', 'C9', '1A', NULL, 54),
  ('S174', 'Emergency Mass-Notification System', 'C9', '1A', NULL, 55),
  ('S204', 'Cybersecurity, Audit & Logging System (System 22)', 'C10', '1A', NULL, 56),
  ('S183', 'Integrated GRC Platform', 'C10', '1A', NULL, 57),
  ('S187', 'Records of Processing Activities (RoPA) Register', 'C10', '1A', NULL, 58),
  ('S191', 'Ethics Hotline / Whistleblower Intake (Institutional)', 'C10', '1A', NULL, 59),
  ('S186', 'Data Subject Access Request (DSAR) Management', 'C10', '1A', NULL, 60),
  ('S188', 'Privacy / Cookie-Consent Management Platform', 'C10', '1A', NULL, 61),
  ('S192', 'Investigation Case Management', 'C10', '1A', NULL, 62),
  ('S185', 'Data Protection Impact Assessment (DPIA) Workflow', 'C10', '1A', NULL, 63),
  ('S196', 'Internal-Audit Working-Paper Software', 'C10', '1A', NULL, 64),
  ('S198', 'ERM Platform — Enterprise Risk Management', 'C10', '1A', NULL, 65),
  ('S201', 'Crisis Management & Incident Communication', 'C10', '1A', NULL, 66),
  ('S222', 'End-User Knowledge Base / Self-Service Portal', 'C11', '1A', NULL, 67),
  ('S205', 'IT Service Management (ITSM) / Service Desk', 'C11', '1A', NULL, 68),
  ('S205_mdm', 'Endpoint Management / MDM', 'C11', '1A', NULL, 69),
  ('S205dev', 'DevOps / CI-CD Toolchain', 'C11', '1A', NULL, 70),
  ('S205scm', 'Source Code Repository & Code Review', 'C11', '1A', NULL, 71),
  ('S206', 'Public-Key Infrastructure & Certificate Lifecycle', 'C11', '1A', NULL, 72),
  ('S207', 'Trust Services / Qualified Digital-Signature Platform', 'C11', '1A', NULL, 73),
  ('S208', 'SIEM (Security Information & Event Management)', 'C11', '1A', NULL, 74),
  ('S208a', 'Observability / APM / Log Aggregation', 'C11', '1A', NULL, 75),
  ('S209', 'Vulnerability Management / Pen-Test Platform', 'C11', '1A', NULL, 76),
  ('S210d', 'Data Loss Prevention (DLP)', 'C11', '1A', NULL, 77),
  ('S212', 'Privileged Access Management (PAM)', 'C11', '1A', NULL, 78),
  ('S213', 'Identity & Access Management (IAM)', 'C11', '1A', NULL, 79),
  ('S220', 'Disaster-Recovery Orchestration / Runbook Automation', 'C11', '1A', NULL, 80),
  ('S220s', 'Secrets Management', 'C11', '1A', NULL, 81),
  ('S221', 'Backup & Immutable Storage Platform', 'C11', '1A', NULL, 82),
  ('S225', 'Analytics Dashboard / Data Warehouse', 'C12', '1A', NULL, 83),
  ('S016', 'Unified Legal Education Portal', 'C1', '1B', 'Carried over from Phase 1', 84),
  ('S017', 'Data Migration & Cutover System', 'C1', '1B', 'Carried over from Phase 1', 85),
  ('S028', 'Student App', 'C3', '1B', 'Carried over from Phase 1', 86),
  ('S029', 'LMS / LPT Platform', 'C3', '1B', 'Carried over from Phase 1', 87),
  ('S030', 'GSL Management Portal', 'C3', '1B', 'Carried over from Phase 1', 88),
  ('S040', 'Industrial Attachment / Pupillage Placement Portal', 'C3', '1B', 'Carried over from Phase 1', 89),
  ('S160', 'Visitor Management System (VMS)', 'C9', '1B', 'Carried over from Phase 1', 90),
  ('S160a', 'Physical Access Control Integration', 'C9', '1B', 'Carried over from Phase 1', 91),
  ('S161', 'CCTV / Video Management System (VMS)', 'C9', '1B', 'Carried over from Phase 1', 92),
  ('S162', 'Intrusion Detection & Alarm Monitoring', 'C9', '1B', 'Carried over from Phase 1', 93),
  ('S162a', 'Fire-Safety & Life-Safety Monitoring', 'C9', '1B', 'Carried over from Phase 1', 94),
  ('S163', 'Health & Safety Incident & Near-Miss Reporting', 'C9', '1B', 'Carried over from Phase 1', 95);
