-- The rest of the 252 Systems Workplan: phases 2A to 4B, plus cluster C13.
-- The countdown covers only the phases listed in settings.countdown_phases.

INSERT INTO clusters (code, name, sort_order) VALUES
  ('C13', 'Monitoring, Evaluation, Benefits Realisation & Continuous Improvement', 13);

INSERT INTO systems (code, name, cluster_code, phase, notes, sort_order) VALUES
  ('S004', 'Digital Archiving System', 'C1', '2A', NULL, 96),
  ('S005', 'Policy Management System', 'C1', '2A', NULL, 97),
  ('S007', 'Legal Education Appeals Tribunal Case Management System', 'C1', '2A', NULL, 98),
  ('S009', 'Roll of Lawyers Integration', 'C1', '2A', NULL, 99),
  ('S091', 'Inspection Management System', 'C2', '2A', NULL, 100),
  ('S093', 'Peer-Reviewer / External-Assessor Roster & Training', 'C2', '2A', NULL, 101),
  ('S095', 'Risk-Based Inspection Scoring Engine', 'C2', '2A', NULL, 102),
  ('S098', 'Continuous-Monitoring Dashboard (between inspections)', 'C2', '2A', NULL, 103),
  ('S031', 'Hostel & Accommodation Management', 'C3', '2A', NULL, 104),
  ('S034', 'Alumni & Member CRM (Bar-Call community)', 'C3', '2A', NULL, 105),
  ('S035', 'Student Discipline & Misconduct Case Management', 'C3', '2A', NULL, 106),
  ('S036', 'Certification & Enrolment System', 'C3', '2A', NULL, 107),
  ('S038', 'Short Courses Platform (System 02)', 'C3', '2A', NULL, 108),
  ('S041', 'Attendance Module (System 04)', 'C3', '2A', NULL, 109),
  ('S042', 'Mentor–Mentee Pairing Platform', 'C3', '2A', NULL, 110),
  ('S048bis_curr', 'Curriculum Mapping & Outcomes Alignment Tool', 'C3', '2A', NULL, 111),
  ('S052_curr', 'Continuing Legal Education (CLE) Credit Tracker', 'C3', '2A', NULL, 112),
  ('S053_curr', 'Knowledge Management & Subject-Matter-Expert (SME) Directory', 'C3', '2A', NULL, 113),
  ('S054_curr', 'Foresight / Horizon-Scanning Workbench', 'C3', '2A', NULL, 114),
  ('S105', 'Discovery Layer / Federated Search', 'C4', '2A', NULL, 115),
  ('S106', 'Institutional Research Repository', 'C4', '2A', NULL, 116),
  ('S109', 'Electronic Resource Management (ERM)', 'C4', '2A', NULL, 117),
  ('S120', 'Off-Campus Authentication Proxy (EZproxy/OpenAthens)', 'C4', '2A', NULL, 118),
  ('S125', 'AI Legal-Research Copilot (RAG)', 'C4', '2A', NULL, 119),
  ('S066', 'Plagiarism & AI-Content Detection Service', 'C5', '2A', NULL, 120),
  ('S078', 'Events Management System (System 08)', 'C6', '2A', NULL, 121),
  ('S080', 'Digital Asset Management (DAM) / Brand Portal', 'C6', '2B', NULL, 122),
  ('S082', 'MOU & Partnership Lifecycle Tracker', 'C6', '2B', NULL, 123),
  ('S083', 'International Relations & Protocols Workspace', 'C6', '2B', NULL, 124),
  ('S084', 'Visa & Travel Authorisation Workflow', 'C6', '2B', NULL, 125),
  ('S088_consult', 'Public-Survey / Consultation Platform', 'C6', '2B', NULL, 126),
  ('S145', 'Learning Experience Platform (LXP) for Staff', 'C7', '2B', NULL, 127),
  ('S136', 'Contract Lifecycle Management (CLM)', 'C8', '2B', NULL, 128),
  ('S137', 'Treasury / Cash Management', 'C8', '2B', NULL, 129),
  ('S147inv', 'Inventory & Stores Management', 'C8', '2B', NULL, 130),
  ('S148', 'Donor Management Module', 'C8', '2B', NULL, 131),
  ('S149', 'IFRS / IPSAS Reporting & Consolidation Module', 'C8', '2B', NULL, 132),
  ('S150', 'Grants Management for Inbound Donor Funding', 'C8', '2B', NULL, 133),
  ('S151_ins', 'Insurance Policy Register', 'C8', '2B', NULL, 134),
  ('S173', 'Event Logistics & Set-Up Workflow', 'C9', '2B', NULL, 135),
  ('S189', 'Internal Control Framework / Control-Test Workflow', 'C10', '2B', NULL, 136),
  ('S195', 'Third-Party / Vendor Risk Management', 'C10', '2B', NULL, 137),
  ('S199', 'Fraud Detection & Forensic Analytics', 'C10', '2B', NULL, 138),
  ('S201bcm', 'Business Continuity Management (BCM) Platform', 'C10', '2B', NULL, 139),
  ('S202', 'Audit Universe & Risk-Based Audit Planning Tool', 'C10', '2B', NULL, 140),
  ('S203', 'Sanctions / PEP / Watchlist Screening', 'C10', '2B', NULL, 141),
  ('S211', 'Configuration Management Database (CMDB)', 'C11', '2B', NULL, 142),
  ('S214', 'Cloud FinOps / Cost Governance', 'C11', '2B', NULL, 143),
  ('S217', 'API & Integration Layer (System 17)', 'C11', '2B', NULL, 144),
  ('S223', 'Master Data Management (MDM) / Data Catalog', 'C11', '2B', NULL, 145),
  ('S224', 'Data Quality & Lineage Tool', 'C11', '2B', NULL, 146),
  ('S247', 'Enterprise M&E Framework (MELF)', 'C13', '2B', 'Establishes the institution-wide monitoring and evaluation architecture: defines KPIs, evaluation cycles, data-collection protocols and reporting chains aligned to CLET''s statutory objects and operational plan.', 147),
  ('S011', 'Gifts, Hospitality & Entertainment Register', 'C1', '3A', NULL, 148),
  ('S014', 'Regulatory Horizon Scanning', 'C1', '3A', NULL, 149),
  ('S092', 'Site-Visit Mobile Field App (offline-capable)', 'C2', '3A', NULL, 150),
  ('S097', 'Public Register of Sanctions / Enforcement Actions', 'C2', '3A', NULL, 151),
  ('S100', 'Standards Benchmarking Database (international)', 'C2', '3A', NULL, 152),
  ('S101', 'Standards-Drafting & Public-Consultation Workspace', 'C2', '3A', NULL, 153),
  ('S103', 'Quality Codes & Indicators Library', 'C2', '3A', NULL, 154),
  ('S043', 'Co-curricular & Society Management', 'C3', '3A', NULL, 155),
  ('S044', 'ID Card, Gown & Physical-Asset Issuance Tracking', 'C3', '3A', NULL, 156),
  ('S045', 'Examiner-of-Practice / Pupil-Master Register', 'C3', '3A', NULL, 157),
  ('S047', 'Translation / Interpretation Booking', 'C3', '3A', NULL, 158),
  ('S050_curr', 'Comparative-Jurisdiction Curriculum Database', 'C3', '3A', NULL, 159),
  ('S051_curr', 'Stakeholder Consultation & Public-Comment Portal', 'C3', '3A', NULL, 160),
  ('S055_curr', 'Pedagogy R&D Sandbox', 'C3', '3A', NULL, 161),
  ('S108', 'Inter-Library Loan (ILL) System', 'C4', '3A', NULL, 162),
  ('S111', 'Authority Control & Legal Taxonomy', 'C4', '3A', NULL, 163),
  ('S118', 'Reading-List Management', 'C4', '3A', NULL, 164),
  ('S121', 'Digital Preservation Platform (Archivematica/Preservica)', 'C4', '3A', NULL, 165),
  ('S124', 'Knowledge Graph / Linked-Data Platform', 'C4', '3A', NULL, 166),
  ('S079', 'Social-Media Management & Listening', 'C6', '3A', NULL, 167),
  ('S085', 'Press / Media Monitoring & Sentiment Analysis', 'C6', '3A', NULL, 168),
  ('S087', 'Webinar / Live-Streaming Platform', 'C6', '3A', NULL, 169),
  ('S091_donor', 'Donor / Annual-Report Microsite Builder', 'C6', '3A', NULL, 170),
  ('S144_career', 'Recruitment Marketing / Career-Site CMS', 'C7', '3A', NULL, 171),
  ('S145b', 'Workforce Planning / Headcount Modelling', 'C7', '3A', NULL, 172),
  ('S145c', 'Compensation Management & Salary Banding', 'C7', '3A', NULL, 173),
  ('S147_perf', 'Performance Management / OKR / 360-Feedback Suite', 'C7', '3B', NULL, 174),
  ('S149_speak', 'Employee Speak-Up / Whistleblower Channel (HR)', 'C7', '3B', NULL, 175),
  ('S151_eng', 'Employee-Engagement Pulse Surveys', 'C7', '3B', NULL, 176),
  ('S153_dei', 'DEI Analytics Dashboard', 'C7', '3B', NULL, 177),
  ('S153_ir', 'Industrial-Relations & Grievance Case Management', 'C7', '3B', NULL, 178),
  ('S154_dis', 'Disciplinary Hearings Workflow', 'C7', '3B', NULL, 179),
  ('S134', 'e-Invoicing / Receivables Automation', 'C8', '3B', NULL, 180),
  ('S139', 'Investment Portfolio Management', 'C8', '3B', NULL, 181),
  ('S144', 'Travel & Expense Management', 'C8', '3B', NULL, 182),
  ('S151fx', 'Foreign Exchange / Multi-Currency Management', 'C8', '3B', NULL, 183),
  ('S156', 'Building Management System (BMS) / IoT', 'C9', '3B', NULL, 184),
  ('S157', 'Energy & Sustainability Monitoring', 'C9', '3B', NULL, 185),
  ('S158', 'Space Planning & Move Management', 'C9', '3B', NULL, 186),
  ('S164', 'Permit-to-Work / Hot-Work Authorisation', 'C9', '3B', NULL, 187),
  ('S165', 'Risk Assessment Library (HSE)', 'C9', '3B', NULL, 188),
  ('S168', 'Asset Tagging / RFID / Barcode Inventory', 'C9', '3B', NULL, 189),
  ('S169', 'Cleaning & Janitorial Schedule Management', 'C9', '3B', NULL, 190),
  ('S190', 'Anti-Bribery & Corruption (ABC) Compliance Platform', 'C10', '3B', NULL, 191),
  ('S195a', 'Vendor / Third-Party IT Risk Platform', 'C10', '3B', NULL, 192),
  ('S197', 'Continuous Auditing / Continuous Monitoring (CA/CM)', 'C10', '3B', NULL, 193),
  ('S202_ins', 'Insurance & Claims Management', 'C10', '3B', NULL, 194),
  ('S208soar', 'SOAR (Security Orchestration, Automation & Response)', 'C11', '3B', NULL, 195),
  ('S214a', 'Container Orchestration & Service Mesh', 'C11', '3B', NULL, 196),
  ('S217a', 'API Gateway, Developer Portal & Catalog', 'C11', '3B', NULL, 197),
  ('S220t', 'Test Management & Automated QA Platform', 'C11', '3B', NULL, 198),
  ('S248', 'KPI Tracking & Benefits Realisation Platform', 'C13', '3B', 'Tracks delivery of planned benefits against each programme, project and strategic initiative across CLET. Maintains a live benefits register, links outcomes to investment cases and flags slippage against baseline.', 199),
  ('S006', 'Policy Lifecycle Workflow with Attestation', 'C1', '4A', NULL, 200),
  ('S099', 'Programme-Level Accreditation Workflow', 'C2', '4A', NULL, 201),
  ('S099d', 'Equivalence & Recognition-of-Prior-Learning (RPL) Workflow', 'C2', '4A', NULL, 202),
  ('S102', 'Stakeholder 360° Survey Engine', 'C2', '4A', NULL, 203),
  ('S033', 'Scholarships, Bursaries & Financial Aid System', 'C3', '4A', NULL, 204),
  ('S037', 'Special Programmes Cohort & Catalogue Engine', 'C3', '4A', NULL, 205),
  ('S039', 'Pre-Call Ceremony / Convocation Management', 'C3', '4A', NULL, 206),
  ('S049_curr', 'Curriculum Version Control & Diff Comparison', 'C3', '4A', NULL, 207),
  ('S107', 'Reference Management & Citation Platform', 'C4', '4A', NULL, 208),
  ('S112', 'DOI / Persistent-Identifier Service', 'C4', '4A', NULL, 209),
  ('S113', 'Rare-Books & Special-Collections Management', 'C4', '4A', NULL, 210),
  ('S114', 'Open-Access & Funder-Mandate Compliance Dashboard', 'C4', '4A', NULL, 211),
  ('S119', 'RFID Self-Issue Kiosks & Stock-Take Hardware', 'C4', '4A', NULL, 212),
  ('S122', 'Plagiarism / Originality Detection (research)', 'C4', '4A', NULL, 213),
  ('S065', 'OSCE / Practical-Skills Assessment Tracker', 'C5', '4A', NULL, 214),
  ('S086', 'Translation & Localisation Management', 'C6', '4A', NULL, 215),
  ('S092_kol', 'Influencer / KOL & Thought-Leader Tracker', 'C6', '4A', NULL, 216),
  ('S093_pod', 'Podcast / Audio Content Platform', 'C6', '4A', NULL, 217),
  ('S142', 'Training & Change Management Platform (System 9D)', 'C7', '4A', NULL, 218),
  ('S145fp', 'Recruitment Marketing — Source Analytics & Talent CRM', 'C7', '4A', NULL, 219),
  ('S146_onb', 'Onboarding Experience Platform', 'C7', '4A', NULL, 220),
  ('S147c_succ', 'Succession Planning & Talent Mapping', 'C7', '4A', NULL, 221),
  ('S148_well', 'Wellness / EAP Portal', 'C7', '4A', NULL, 222),
  ('S150_vol', 'Volunteering / Pro-Bono Hours Tracker', 'C7', '4A', NULL, 223),
  ('S151_exit', 'Exit Interview & Offboarding Workflow', 'C7', '4A', NULL, 224),
  ('S152_rew', 'Reward & Recognition / Peer-Kudos Platform', 'C7', '4A', NULL, 225),
  ('S145p', 'Imprest, Petty-Cash & Card-Spend Module', 'C8', '4A', NULL, 226),
  ('S146fp', 'Budget Planning, Forecasting & FP&A', 'C8', '4B', NULL, 227),
  ('S150c', 'Crowdfunding / Alumni Giving Portal', 'C8', '4B', NULL, 228),
  ('S150d', 'Donor & Grant Compliance Reporting Workspace', 'C8', '4B', NULL, 229),
  ('S150sp', 'Sponsorship & Membership Subscriptions Management', 'C8', '4B', NULL, 230),
  ('S151c', 'Cost-Recovery / Inter-Directorate Chargeback Engine', 'C8', '4B', NULL, 231),
  ('S167', 'GPS / Telematics Tracking', 'C9', '4B', NULL, 232),
  ('S168a', 'Trip / Driver-Booking Portal', 'C9', '4B', NULL, 233),
  ('S170', 'Pest-Control & Hygiene Audit Tracker', 'C9', '4B', NULL, 234),
  ('S172', 'Catering & Cafeteria Management', 'C9', '4B', NULL, 235),
  ('S175', 'Crisis & Evacuation Drill Management', 'C9', '4B', NULL, 236),
  ('S176', 'Construction Project Management', 'C9', '4B', NULL, 237),
  ('S177', 'Lease & Tenancy Management', 'C9', '4B', NULL, 238),
  ('S178', 'Waste Management & Recycling Tracking', 'C9', '4B', NULL, 239),
  ('S179', 'Lost-and-Found Register', 'C9', '4B', NULL, 240),
  ('S200', 'Risk Bow-Tie / Heat-Map Visualisation', 'C10', '4B', NULL, 241),
  ('S205_inv', 'Internal Investigations Mobile Speak-Up App', 'C10', '4B', NULL, 242),
  ('S205byod', 'Mobile Device & BYOD Policy Engine', 'C11', '4B', NULL, 243),
  ('S205lic', 'Software Licence Management', 'C11', '4B', NULL, 244),
  ('S215', 'Innovation Sandbox / Experimentation Environment', 'C11', '4B', NULL, 245),
  ('S226', 'Self-Service BI Tooling', 'C12', '4B', NULL, 246),
  ('S227', 'Predictive / Prescriptive Models — at-risk Students, Bar-pass propensity', 'C12', '4B', NULL, 247),
  ('S228', 'Responsible-AI Governance Workspace', 'C12', '4B', NULL, 248),
  ('S249', 'Institutional Performance Review System', 'C13', '4B', 'Manages the CLET-wide periodic performance review cycle: schedules reviews, captures self-assessment returns from each directorate, consolidates findings and produces the statutory annual performance report for the Board and the Minister.', 249),
  ('S250', 'Process Improvement & Lessons-Learned Repository', 'C13', '4B', 'Captures, classifies and disseminates lessons learned from projects, audits, inspections and service delivery. Supports root-cause analysis and hosts improvement action plans with tracked completion status.', 250),
  ('S251', 'Value Tracking & Continuous Service Enhancement Dashboard', 'C13', '4B', 'Provides a real-time operational dashboard for ongoing service performance: tracks SLAs, user-satisfaction scores, system uptime and process cycle times across all 252 digital systems. Enables data-driven continuous improvement decisions.', 251),
  ('S252', 'M&E Governance & Quality Assurance Framework Tool', 'C13', '4B', 'Embeds governance controls into the M&E lifecycle: enforces data-quality standards on indicator inputs, validates evaluation methodology, maintains an audit trail of all M&E reports, and flags non-compliant data submissions for remediation.', 252);

ALTER TABLE settings ADD COLUMN countdown_phases text[] NOT NULL DEFAULT '{1A,1B}';
