-- Readiness snapshot taken from the working database on 8 Oct 2026: go-live decisions from
-- the Release 1 Phased Schedule (4 Oct 2026) and the readiness statuses set by admins.
-- Lets a fresh deployment start from the same state.

UPDATE systems SET status = 'ready', go_live = 'yes', notes = 'Release 1 Wave 1 candidate: ready with conditions; go/no-go 14 Oct' WHERE code = 'S001';
UPDATE systems SET status = 'ready', go_live = 'yes', notes = NULL WHERE code = 'S002';
UPDATE systems SET status = 'ready', go_live = 'yes', notes = 'Release 1 Wave 1 candidate: ready with conditions; go/no-go 14 Oct' WHERE code = 'S003';
UPDATE systems SET status = 'ready', go_live = 'yes', notes = NULL WHERE code = 'S010';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S015';
UPDATE systems SET status = 'not_ready', go_live = 'yes', notes = NULL WHERE code = 'S012';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S008';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S013';
UPDATE systems SET status = 'not_ready', go_live = 'yes', notes = NULL WHERE code = 'S094';
UPDATE systems SET status = 'not_ready', go_live = 'yes', notes = 'Release 1 Wave 1 candidate: ready with conditions; go/no-go 14 Oct' WHERE code = 'S048';
UPDATE systems SET status = 'not_ready', go_live = 'yes', notes = NULL WHERE code = 'S096';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S099b';
UPDATE systems SET status = 'not_ready', go_live = 'yes', notes = NULL WHERE code = 'S099c';
UPDATE systems SET status = 'not_ready', go_live = 'yes', notes = 'Release 1 Wave 1 candidate: ready with conditions; go/no-go 14 Oct' WHERE code = 'S027';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S032';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S046';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = 'Yet to decouple' WHERE code = 'S104';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = 'Yet to decouple' WHERE code = 'S110';
UPDATE systems SET status = 'not_ready', go_live = 'yes', notes = 'Release 1 Wave 1 candidate: ready with conditions; go/no-go 14 Oct' WHERE code = 'S060';
UPDATE systems SET status = 'not_ready', go_live = 'yes', notes = 'Release 1 Wave 1 candidate: ready with conditions; go/no-go 14 Oct' WHERE code = 'S061';
UPDATE systems SET status = 'not_ready', go_live = 'yes', notes = 'Release 1 Wave 1 candidate: ready with conditions; go/no-go 14 Oct' WHERE code = 'S063';
UPDATE systems SET status = 'not_ready', go_live = 'tbd', notes = 'Follows after 15 Oct unless closed in time: desktop sign-in; load test of a full sitting' WHERE code = 'S064';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S067';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S068';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S069';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S062';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = 'Clarification from SRS Team Needed' WHERE code = 'S090_crisis';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S089';
UPDATE systems SET status = 'not_ready', go_live = 'yes', notes = 'Release 1 Wave 1 candidate: ready with conditions; go/no-go 14 Oct' WHERE code = 'S074';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S075';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S076';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S077';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S081';
UPDATE systems SET status = 'not_ready', go_live = 'tbd', notes = 'HRMS (minimal). Follows after 15 Oct unless closed in time: minimal-scope control; board-register sync to Governance; a passing build' WHERE code = 'S140';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S143';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S145_bgc';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S148_time';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S149_pen';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S150_tax';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S141_pay';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S132';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S133';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S135';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S138';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S140fin';
UPDATE systems SET status = 'not_ready', go_live = 'yes', notes = 'Release 1 Wave 1 candidate: ready with conditions; go/no-go 14 Oct' WHERE code = 'S141';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S147';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S190fin';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S152';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S153';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S159';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S166';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S168_fuel';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S171';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S174';
UPDATE systems SET status = 'not_ready', go_live = 'tbd', notes = 'Audit trail (CALS). Follows after 15 Oct unless closed in time: acceptance of audit events from every system; an audited restart procedure' WHERE code = 'S204';
UPDATE systems SET status = 'not_ready', go_live = 'yes', notes = 'Release 1 Wave 1 candidate: ready with conditions; go/no-go 14 Oct' WHERE code = 'S183';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S187';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S191';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S186';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S188';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S192';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S185';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S196';
UPDATE systems SET status = 'not_ready', go_live = 'yes', notes = 'Release 1 Wave 1 candidate: ready with conditions; go/no-go 14 Oct' WHERE code = 'S198';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S201';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S222';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S205';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S205_mdm';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S205dev';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S205scm';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S206';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S207';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S208';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S208a';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S209';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S210d';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S212';
UPDATE systems SET status = 'ready', go_live = 'yes', notes = 'Release 1 Wave 1 candidate: ready with conditions; go/no-go 14 Oct' WHERE code = 'S213';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S220';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S220s';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = NULL WHERE code = 'S221';
UPDATE systems SET status = 'not_ready', go_live = 'tbd', notes = 'Not ready for Release 1 (phased schedule, 4 Oct)' WHERE code = 'S225';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = 'Carried over from Phase 1' WHERE code = 'S016';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = 'Carried over from Phase 1' WHERE code = 'S017';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = 'Carried over from Phase 1' WHERE code = 'S028';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = 'Carried over from Phase 1' WHERE code = 'S029';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = 'Carried over from Phase 1' WHERE code = 'S030';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = 'Carried over from Phase 1' WHERE code = 'S040';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = 'Carried over from Phase 1' WHERE code = 'S160';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = 'Carried over from Phase 1' WHERE code = 'S160a';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = 'Carried over from Phase 1' WHERE code = 'S161';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = 'Carried over from Phase 1' WHERE code = 'S162';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = 'Carried over from Phase 1' WHERE code = 'S162a';
UPDATE systems SET status = 'not_ready', go_live = 'no', notes = 'Carried over from Phase 1' WHERE code = 'S163';
UPDATE systems SET status = 'not_ready', go_live = 'yes', notes = 'Release 1 Wave 1 candidate: ready with conditions; go/no-go 14 Oct' WHERE code = 'S007';
UPDATE systems SET status = 'ready', go_live = 'yes', notes = 'Release 1 Wave 1 candidate: ready with conditions; go/no-go 14 Oct' WHERE code = 'S217';
